export const FETCHING_OPPORTUNITIES = "FETCHING_OPPORTUNITIES";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";
export const FETCHING_OPPORTUNITIES_SUCCESS = "FETCHING_OPPORTUNITIES_SUCCESS";
export const SAVE_OPPORTUNITIES = "SAVE_OPPORTUNITIES";
export const opportunityPath = '/opportunities';